name: Advent of Code 2025

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/2025.yml
      - 2025/**
  pull_request:
    paths:
      - .github/workflows/2025.yml
      - 2025/**

jobs:
  build-2025:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "2025"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
